title: iMoses.co
url: http://imoses.co

collections:
  projects:
    output: true
    permalink: /:collection/:slug

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: projects
    values:
      layout: project

sass:
  style: compressed

exclude: [.idea]
